apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-ml
  labels:
    app: project-ml
spec:
  selector:
    matchLabels:
      app: project-ml
  template:
    metadata:
      labels:
        app: project-ml
    spec:
      containers:
      - name: project-ml
        image: michaelsorenson/udacity-project-ml:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: project-ml
spec:
  selector:
    app: project-ml
  ports:
    - protocol: TCP
      port: 80
